version: '3.8'

services:
  db:
    container_name: postgres-java-league
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: java_league
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "15432:80"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
